language: node_js
node_js:
- '0.11'
install:
- npm install
deploy:
  provider: s3
  bucket: tatu-error-pages
  secret_access_key:
    secure: KGf0MFVfQq8cOAx4DNWmwYPNh3wIWqiStA0zq+OpxFmGurV+mmpkRFFHjo47xipeSLlrM6ep7RaG9cFXA2Y0oFwth27mvY8mxozVzg5ED8SGdGMRcxBt3DXAzg4pwuFJ5AURFtvTvFORT/2fzoLqIT3Bb+ISEsKTtBGmpzVuzUI=
  access_key_id:
    secure: P2A4tcJ5I2ebTr9VOhXOv37SDaJswutWZOsEPho8Q+O1V9yLcXYRqA5mD7kSkIO0qha30K4owTBPfMvkfXUsu0mfX+34fYMt6WmZ/NVRp72jQ34lDoMkhAMPMq0Pd6H+JL4xDxtwhcSV/b7O/pUoDxMZPJapuHVqWMwvngKDuvU=
